from enum import Enum


class ConnectionState(Enum):
    NOT_CONNECTED = 1
    CONNECTED_NOT_LOGGED_IN = 2
    CONNECTED_READY_FOR_LOGIN_ATTEMPT = 3
    CONNECTED_LOGIN_INCORRECT = 4
    CONNECTED_LOGGED_IN = 5
    CONNECTED_READY_FOR_COMMAND = 6
    DISCONNECTING = 7
